### 1. LOGIN (OBTENER TOKEN)
# (Ejecutá este y copiá el token de la respuesta)
POST http://localhost:3000/api/login
Accept: application/json
Content-Type: application/json

{
    "usuario": "admin",
    "password": "1234"
}

### -------------------------

### 2. GET USERS (plural)
# (Pegá el token acá abajo)
GET http://localhost:3000/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTFhYzk4N2Y3ZGZjMWQyMzA3YWQ4NWQiLCJ1c3VhcmlvIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NjMzNjU4MDgsImV4cCI6MTc2MzM5NDYwOH0.yfGllz9BLHAgGkUgE4Vflocfu6WN6EP2dzGaQ9IUYGE

### -------------------------

### 3. CREATE USER (plural)
# (Pegá el token acá abajo)
POST http://localhost:3000/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTFhYzk4N2Y3ZGZjMWQyMzA3YWQ4NWQiLCJ1c3VhcmlvIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NjMzNjU4MDgsImV4cCI6MTc2MzM5NDYwOH0.yfGllz9BLHAgGkUgE4Vflocfu6WN6EP2dzGaQ9IUYGE
Content-Type: application/json

{
    "usuario": "nuevo_op",
    "password": "12345",
    "nombre": "Nuevo Cliente",
    "roles": ["cliente"],
    "email": "nuevo@fake.com"
}

### -------------------------

### 4. DELETE USER (plural)
# (Pegá el token acá abajo)
DELETE http://localhost:3000/api/users/00000000-0000-0000-0000-000000000001
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTFhYzk4N2Y3ZGZjMWQyMzA3YWQ4NWQiLCJ1c3VhcmlvIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NjMzNjU4MDgsImV4cCI6MTc2MzM5NDYwOH0.yfGllz9BLHAgGkUgE4Vflocfu6WN6EP2dzGaQ9IUYGE


### ACTUALIZAR TOKEN CUANDO SE VAYA A USAR